### ISSUE TITLE
The "TAAR v3" shield study does not have an icon displayed in the "about:addons" page

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/taar-experiment-v3-shield-study#37]
**[Affected versions]:**
- Firefox 61.0

**[Affected Platforms]:**
- All Windows
- All Linux
- All Mac

**[Prerequisites]:**
- Have a new Firefox profile with the latest version of the "TAAR v3" add-on (downloaded from https://bugzilla.mozilla.org/show_bug.cgi?id=1469546) installed.
- Create the following prefs in the "about:config" page:
	- "shieldStudy.logLevel" as string and set it to "All";
	- "extensions.taarexpv3_shield_mozilla_org.test.variationName" as string and set it to "control", "intervention-a" or "intervention-b"

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Navigate to "about:addons>Extensions" and observe the left side of the add-on's name.

**[Expected result]:**
- There is an icon displayed.

**[Actual result]:**
- There is an empty space in the front of the add-on's name.

**[Notes]:**
- Until now we have not encountered a shield study or an add-on without an icon in the "about:addons" page.
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/42157692-1030ccca-7df7-11e8-80f0-dfb3829d3146.gif)

**Comment by Softvision-MariusComan** [comment]
I have retested this issue and it seems that it is partially fixed. Now there is an icon displayed in the front of the add-on's name, but it is too small comparative with another add-ons icons.
Tested on Windows 10 x64, Mac 10.13 and Arch Linux, with the latest version of the "TAAR v3" add-on (3.0.2) installed on latest Firefox release (61.0.1) and latest Firefox Beta (62.0b7).

**Comment by motin** [comment]
This seems to be related to a bug in Firefox, since even with https://github.com/motin/taar-experiment-v3-shield-study/commit/d34abe28f7089030d7294232e03ea8ec69b774bf, this remains the case:
<img width="841" alt="add-ons_manager_and_browser_console" src="https://user-images.githubusercontent.com/793037/42588520-68a568fe-853e-11e8-9610-146ec96dc7f9.png">
@Softvision-MariusComan 
I had to generate and [use fixed-size png icons](https://github.com/motin/taar-experiment-v3-shield-study/commit/3dac246dec10eb928870619d85de368c3beb7507) for the icon to show correctly in about:addons:
<img width="841" alt="add-ons_manager_and_browser_console" src="https://user-images.githubusercontent.com/793037/42593988-2a8fa808-854e-11e8-9d71-14810a55f72e.png">

**Comment by Softvision-MariusComan** [comment]
This issue is no longer reproducible with the latest version of the "TAAR v3" add-on (3.0.3) installed on latest Firefox release (61.0.1) and latest Firefox Beta (62.0b7). Verified on Windows 10 x64, Mac 10.13 and Arch Linux.
Considering the above I am closing this issue.
